name: Android CI

on:
  push:
    branches: [ "sjxs" ]
  pull_request:
    branches: [ "sjxs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
[![Android CI](https://github.com/xinyi1984/TV/actions/workflows/android.yml/badge.svg?branch=sjxs)](https://github.com/xinyi1984/TV/actions/workflows/android.yml)
