name: fongmi4.4 Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4  # Use the latest version of setup-node
        with:
          node-version: 12  # Explicitly set Node.js version to 12

      - uses: actions/checkout@v2 

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Release Apk Sign
        run: |
          signingConfigs='c2lnbmluZ0NvbmZpZ3Mge1wKICAgICAgICBpZiAocHJvamVjdC5oYXNQcm9wZXJ0eSgiRk9OR01JNFhfU1RPUkVfRklMRSIpKSB7XAogICAgICAgICAgICBteUNvbmZpZyB7XAogICAgICAgICAgICAgICAgc3RvcmVGaWxlIGZpbGUoRk9OR01JNFhfU1RPUkVfRklMRSlcCiAgICAgICAgICAgICAgICBzdG9yZVBhc3N3b3JkIEZPTkdNSTRYX1NUT1JFX1BBU1NXT1JEXAogICAgICAgICAgICAgICAga2V5QWxpYXMgRk9OR01JNFhfS0VZX0FMSUFTXAogICAgICAgICAgICAgICAga2V5UGFzc3dvcmQgRk9OR01JNFhfS0VZX1BBU1NXT1JEXAogICAgICAgICAgICAgICAgdjFTaWduaW5nRW5hYmxlZCB0cnVlXAogICAgICAgICAgICAgICAgdjJTaWduaW5nRW5hYmxlZCB0cnVlXAogICAgICAgICAgICAgICAgZW5hYmxlVjNTaWduaW5nID0gdHJ1ZVwKICAgICAgICAgICAgICAgIGVuYWJsZVY0U2lnbmluZyA9IHRydWVcCiAgICAgICAgICAgIH1cCiAgICAgICAgfVwKICAgIH1cClw='
          signingConfig='aWYgKHByb2plY3QuaGFzUHJvcGVydHkoIkZPTkdNSTRYX1NUT1JFX0ZJTEUiKSkge1wKICAgICAgICAgICAgICAgIHNpZ25pbmdDb25maWcgc2lnbmluZ0NvbmZpZ3MubXlDb25maWdcCiAgICAgICAgICAgIH1c'
          signingConfigs="$(echo "$signingConfigs" |base64 -d )"
          signingConfig="$(echo "$signingConfig" |base64 -d )"
          sed -i -e "/defaultConfig {/i\\$signingConfigs " -e "/debug {/a\\$signingConfig " -e "/fongmi4x {/a\\$signingConfig " app/build.gradle
          cp -f ${{ github.workspace }}/.github/workflows/TVBoxOSC.jks app/TVBoxOSC.jks
          sed -i '$a\FONGMI4X_STORE_FILE=./TVBoxOSC.jks'     ./gradle.properties
          sed -i '$a\FONGMI4X_ALIAS=TVBoxOSC'            ./gradle.properties
          sed -i '$a\FONGMI4X_STORE_PASSWORD=TVBoxOSC'       ./gradle.properties
          sed -i '$a\FONGMI4X_KEY_PASSWORD=TVBoxOSC'         ./gradle.properties

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean assembleRelease --parallel --daemon --warning-mode all --stacktrace

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find . -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v2
        with:
          name: com.github.tvbox.fongmi4x
          path: ${{ github.workspace }}/apk/*

