# .github/workflows/sync.yml
name: Sync Fork

on:
  push: # push 时触发, 主要是为了测试配置有没有问题
  schedule:
    - cron: '* */3 * * *' # 每3小时触发, 对于一些更新不那么频繁的项目可以设置为每天一次, 低碳一点
  workflow_dispatch: # on button click
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          github_token: ${{ secrets.SYNC_TOKEN }}
          owner: FongMi # fork 的上游仓库 user
          head: release # fork 的上游仓库 branch
          base: release # 本地仓库 branch
